### ISSUE TITLE
text_color

### ISSUE THREAD

**Issue by rdbrown** [Retsly/retsly-android-sample-app#1]
The file text_color is missing an extension under retsly-android-sample-app/app/src/main/res/color.  The file name should text_color.xml. It needs the extension to build in android studio.

**Comment by RongxinZhang** [comment]
@rdbrown Awesome, if you'd like to open a PR I can get it reviewed 👍

**Comment by rdbrown** [comment]
https://github.com/rdbrown/retsly-android-sample-app/pull/1

Done

**Comment by MadManMathew** [comment]
@rdbrown you actually submitted a pull-request on your fork (would you like to fix it or I could update it for you). I noticed the file is actually there but it doesn't have .xml extension

**Comment by rdbrown** [comment]
Sure. I can fix it.

Donna

**Comment by rdbrown** [comment]
Just tried but github said I don't have access to upload a new file. The
file just needs to be renamed with .xml.  I am happy to do it, if you allow
access to rename the file.

Thanks,
Donna

**Comment by RongxinZhang** [comment]
@rdbrown have you tried doing a pull request against our repo by: https://help.github.com/articles/using-pull-requests/#changing-the-branch-range-and-destination-repository

**Comment by rdbrown** [comment]
I did a pull request again your repo following the instructions from the
link. Please let me know if I made a mistake.

Thanks,

Donna
